AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*.rb"
    - "spec/services/*.rb"
    - "spec/models/*.rb"

Style/Documentation:
  Enabled: false
