AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*.rb"
    - "spec/services/*.rb"
    - "spec/models/*.rb"

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Style/Documentation:
  Enabled: false
