version: "3"
services:
  redis:
    image: redis
    ports:
      - "6380:6380"
    command: redis-server --port 6380 --appendonly yes
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-desconto_inss_development}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  web:
    build: .
    volumes:
      - .:/desconto_inss
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: postgres
      REDIS_URL: redis://redis:6380
      RAILS_ENV: ${RAILS_ENV:-development}
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/desconto_inss
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-desconto_inss_development}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      REDIS_URL: redis://redis:6380
      RAILS_ENV: ${RAILS_ENV:-development}
volumes:
  postgres:
